### PR TITLE
Add instructions for setting up vscode integration

### PR DESCRIPTION
**Pull request by wadetandy**

### CODE REVIEW

**Comment by wadetandy** [comment]
Fixes #125

**Comment by penelopezone** [comment]
Hi @wadetandy I think unfortunately this doesn't work! If you look at `https://github.com/rubyide/vscode-ruby/blob/master/packages/language-server-ruby/src/formatters/RubyFMT.ts#L4` they vendor rubyfmt.rb (the legacy, broken) version of Rubyfmt in to their plugin. We should ask them either to update to point at the rust version or build our own plugin

**Comment by wadetandy** [comment]
ahh interesting, didn't realize. I had run it against a few files in my project, but I guess the formatting issues were simple enough that this older bundled version worked fine. Opened an issue with the extension, so we can hopefully get the discrepancy resolved.

**Comment by wadetandy** [comment]
@penelopezone Have opened [a PR](https://github.com/rubyide/vscode-ruby/pull/628) for vscode-ruby which the formatter to rely on a rubyfmt available on PATH.  As that doesn't work correctly with an alias, I've also updated this PR to include a script for generating a shim executable instead in place of a bash alias.  Glad to update it and/or the README however you'd like.

**Comment by wadetandy** [comment]
Updated with a test for stdin processing, since I had separately started adding this for necessity with vscode integration and realized you'd already done it. Since I'd already written the test I figured I'd include it.

**Comment by wadetandy** [comment]
Hey @penelopezone. Any feedback around why this was closed? Would love to figure out a path forward on supporting vscode and being able to leverage the existing plugin seems like the quickest path forward. Glad to rework this however you'd like, however.

**Comment by fables-tales** [comment]
OH! This was closed because I deleted the master branch and rebased all the commits to remove my deadname. You should retarget main and be able to re-open it! I didn't mean to close this :) Sorry for the churn! This looks great, full review in a bit.

**Comment by wadetandy** [comment]
Ahh makes sense. Reopened #204 to address.

**Pull request closed without merging**
