### PR TITLE
Rename to "ruby format"

### PR DESCRIPTION
**Pull request by samphippen**

### CODE REVIEW

**Comment by searls** [comment]
My vote is `rubyfmt`, because it's shorter, more distinctive, and it will take people 2 seconds to learn and remember. 

Note: I really don't care that it's a nod to `gofmt` and I'll never pronounce the `fmt` as "foomt" because I am a Proper English Speaker™

**Comment by samphippen** [comment]
I think the binary name (once we actually ship binaries lmao) can still be `rubyfmt`, but I want to make it clear the project is named "Ruby Format"

**Comment by twe4ked** [comment]
“Ruby Format” is different to rubyformat though. This feels confusing now because there are 3 (or 4 depending on casing) ways to refer to this project.

- rubyfmt
- rubyformat
- ruby format
- Ruby Format

**Comment by samphippen** [comment]
Hi @twe4ked this issue is closed favouring #144. Don't worry.

**Pull request closed without merging**
