### PR TITLE
Make defs work with memoist-style definitions

### PR DESCRIPTION
**Pull request by fables-tales**
/cc @samandmoore

### CODE REVIEW

**Comment by samandmoore** [comment]
Yay! Lemme know when you want me to try to break this thing some more @penelopezone 😁

**Comment by timriley** [comment]
It's nice to see that these method "annotations" will work, thank you @penelopezone!

If you don't mind, I have a question about this PR — is the structure demonstrated in `memoist_expected.rb`:

- Just a temporary state, demonstrating that things are at least _working_ right now, but with a view to having rubyfmt eventually preserve the original structure shown in `memoist_actual.rb`?
- Or is it the way you want rubyfmt to format these things for the long run?

Thank you!

**Comment by penelopezone** [comment]
@timriley nothing is final right now. That said:

* This style of method definition is pretty uncommon (I'd literally never seen it before @samandmoore showed me the example, and I've been doing Ruby for > 10 years).
* Rubyfmt is a "prefers no special cases" formatter
* Rubyfmt always prints parentheses on method calls
* I think this form would be pretty ugly:
```ruby
memoize(def foo
end)

so, I'm disinclined to special case definitions of this form right now, but I am open to changing my mind.

**Comment by timriley** [comment]
Thanks for explaining your thinking, @penelopezone 🙏 

So I've done that `memoize def foo` thing a fair bit – specifically with memoizing helper gems – ever since the Ruby 2.1 change for method definitions to return a symbolised name, mostly because I liked the concision of it.

I recognise it's perhaps a somewhat unusual approach (evidenced even by how it can break the syntax highlighting in certain editors), but I'm happy to offer this as an anecdotal data point for you at least.

If a tool like rubyfmt (and I'm super keen to adopt it) wound up re-formatting them to this structure:

```ruby
memoize(
  def foo(x,y,z)
    # ...
  end
)
```

Then I think I'd have to give up the approach entirely, since the concision has gone out the window by that point!

I'm definitely not saying my one piece of feedback should force you to change the approach, but I do think it's a nice little piece of expressiveness we lose by not having this special-cased (though I also realise this is a slippery slope to go down - I'll leave it with you from here).

FWIW I think I've also seen Avdi use this "method annotation style" with `private def foo(x,y,z)` too... IIRC you and he might've had a Twitter convo about it.

**Pull request merged**
